feat: new joinSpectraData() function
rformassspectrometry/Spectra pull request #160
Opened 2020-11-04 15:34 UTC by lgatto

2020-11-04 15:35 UTC, lgatto commented
This PR addressed #149

2020-11-05 08:31 UTC, jorainer requested changes
Great addition, thanks @lgatto . I have some minor change requests in the documentation. Also, could you please add an example of the function to the examples of `Spectra`? And lastly, please bump the version as I have pushed the version already to Bioconductor.

2020-11-05 08:31 UTC, jorainer commented on R/Spectra.R
> +#' - `joinSpectraData`: Individual spectra data variable can be
I would suggest to change that sentence to: `individual spectra variables can be...`.

2020-11-05 08:31 UTC, jorainer commented on R/Spectra.R
> +#'    `merge()` method in two main ways:
`[merge()]` instead of `merge()` to add the link to the `merge` help page.

2020-11-05 08:31 UTC, jorainer commented on R/Spectra.R
> +#' @param by.x A `character(1)` specifying of the spectra variable
Please remove the `of`.

2020-11-05 08:31 UTC, jorainer commented on R/Spectra.R
> +#' @param by.y A `character(1)` specifying of the column used for
Also here, please remove `of`

2020-11-05 09:01 UTC, lgatto commented
- I had an example ready but forgot to add it in the end. Will be done in next PR.
- Will bump version - hadn't realised it was pushed to Bioc. I would suggest whoever pushed to Bioc bump on Github and mentions 'nothing yet' in the NEWS file.

2020-11-05 09:21 UTC, lgatto commented
I also fixed a missing export statement. 

@jorainer - feel free to merge if you are happy with the PR.

2020-11-05 09:46 UTC, jorainer approved these changes
All fine, thanks @lgatto!

2020-11-05 09:58 UTC, merged

2020-11-05 09:59 UTC, jorainer commented
And pushed to BioC

2020-11-05 10:01 UTC, lgatto commented
There is an issue with checks, which I didn't have locally. I'm investigating.

2020-11-05 10:05 UTC, jorainer commented
No worries - it's because the new docker image with Bioconductor 3.13 is not yet working properly (I think the `DelayedArray` package is not available yet).

2020-11-05 11:37 UTC, jorainer commented
Actually, seems it's more the `msdata` and the `vdiffr` packages. Install/download of `msdata` fails due to a corrupt download also for me:
```r
> BiocManager::install("msdata")
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable)
  (2020-10-24 r79367)
Installing package(s) 'msdata'
trying URL 'https://bioconductor.org/packages/3.13/data/experiment/src/contrib/msdata_0.31.0.tar.gz'
Content type 'application/x-gzip' length 446179202 bytes (425.5 MB)
===========================
downloaded 237.2 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.13/data/experiment/src/contrib/msdata_0.31.0.tar.gz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 248742946 != reported length 446179202
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://bioconductor.org/packages/3.13/data/experiment/src/contrib/msdata_0.31.0.tar.gz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘msdata’ failed

```

2020-11-05 12:06 UTC, lgatto commented
This seems a temporary glitch - I was able to re-install that same version of `msdata` locally:

```r
> packageVersion("msdata")
[1] ‘0.31.0’
> BiocManager::install("msdata")
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable)
  (2020-04-28 r78328)
Installing package(s) 'msdata'
trying URL 'https://bioconductor.org/packages/3.13/data/experiment/src/contrib/msdata_0.31.0.tar.gz'
Content type 'application/x-gzip' length 446179202 bytes (425.5 MB)
==================================================
downloaded 425.5 MB

* installing *source* package ‘msdata’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (msdata)

The downloaded source packages are in
	‘/tmp/RtmpzHuMM8/downloaded_packages’
Installation path not writeable, unable to update packages: codetools,
  KernSmooth
> packageVersion("msdata")
[1] ‘0.31.0’
```

2020-11-05 12:15 UTC, jorainer commented
I get the same error again and again (although the size of the downloaded file differs). I'm wondering if this might have to do with the current developmental version of R (i.e. 4.1).