Added 'reduceSpectra' function
rformassspectrometry/Spectra pull request #286
Opened 2023-05-11 09:34 UTC by AharoniLab

Please evaluate the preliminary version for deisotoping spectra: #282

2023-05-16 11:44 UTC, jorainer commented
This PR adds the functions discussed in issues #282 and #283

2023-05-17 09:44 UTC, lgatto requested changes
Could you also please update the NEWS file accordingly.

2023-05-17 09:44 UTC, lgatto commented on R/Spectra-functions.R
> +    addProcessing(x, .peaks_deisotope, tolerance = tolerance, ppm = ppm,
Please indent all lines the same way.

2023-05-17 09:44 UTC, lgatto commented on R/Spectra.R
> +#'   determined using data from the Human Metabolome Database (HMDB) and
May be add a reference or link to provide more information about *the default parameters for isotope prediction/detection have been determined using data from HMDB*.

2023-05-17 09:44 UTC, lgatto commented on R/peaks-functions.R
> +#' @author Nir Shahaf, Johannes Rainer
May be document the `x` param here with the following (taken from the isotopologues documentation)
```
@param x `matrix` with spectrum data (columns `mz` and `intensity`).
```
and point to `MetaboCoreUtils::isotopologues()` for more details.

2023-05-17 09:44 UTC, lgatto commented on R/peaks-functions.R
> +.peaks_reduce <- function(x, tolerance = 0, ppm = 10, ...) {
As above, I would suggest to document `x`.

2023-05-17 10:39 UTC, jorainer commented
@lgatto all points have been addressed now. Thanks for the review.

2023-05-17 10:47 UTC, lgatto approved these changes

2023-05-17 10:47 UTC, lgatto commented
Thank you for the contribution!

2023-05-17 11:12 UTC, merged