Introducing `filterRanges` Function and Discussion on a possible `filterSimilarities`
rformassspectrometry/Spectra pull request #312
Opened 2024-02-15 12:47 UTC by philouail

Hi, I wanted to suggest the implementation of this function `filterRanges`, which allows the user to filter a `spectra` object based on any variables of its `spectraData` suing a range of values that the user inputs . I believe this would be great for multiple reasons:

- Allow multiple filtering to happen at the same time.
- Allow for seamless integration of filtering based on any future-added or user-specific spectraData variable.
- Prevent the creation of many variable-specific filtering functions in the future.

Welcoming any feedback on the code and PR :)

On the other hand, I would also like to suggest implementing a similar function such as `filterSimilarities` (not sure about the name), which would be implemented in a similar way for filtering based on *similarity* to specific values for variables within the `spectraData` of the object rather than within a range. Thus, it would have the same advantages as the `filterRanges` function. It would prevent variable-specific functions and make the code easier to combine multiple filters.

I can however see the counter argument that this might not be as user-friendly as variable-specific functions. I would love to get your opinion @jorainer and @lgatto on this. If you are interested i can come up with a more detailed proposition of implementation.

2024-02-16 08:01 UTC, jorainer requested changes
Thank you @philouail ! Great PR! Some change requests and questions.

Also, something strange happened with the roxygen documentation.

2024-02-16 08:04 UTC, jorainer commented
To me this function is great and also the `filterSimilarities` - that I would rather suggest to call `filterValues` would make a lot of sense to me. @lgatto what's your opinion on that?

We have already a use case in which we want to extract/filter spectra with their precursor m/z and retention time within respective ranges (from MS1 data).

2024-02-16 09:34 UTC, philouail commented on R/Spectra.R
> +              idc <- which(rowSums(within_ranges, na.rm = FALSE) == nc)
No I think `vapply` is different from `sapply` and `lapply` by also the fact that it return a matrix/array that depends on the specified output (here a logical of length `now(query)`), it is also *always* simplified compared to the other apply function from what i understand. so ye, the code is a bit weird with `vapply` but the output is perfect as it is directly a matrix and also much much faster than using for loop (did a little benchmarking).

2024-02-16 09:36 UTC, philouail commented on R/Spectra.R
> +#'    based on specified ranges for *any* values of `spectraVariables(object)`.
True, I forgot about adding something to the vignette ! Maybe I can wait until we decide to implement or not the second function to show an example ? 

I also detailed more the example in the meantime.

2024-02-16 10:14 UTC, philouail commented
Thanks @jorainer ! I have adapted the code to your suggestions.

2024-02-19 12:10 UTC, jorainer commented on R/Spectra.R
> +              idc <- which(rowSums(within_ranges, na.rm = FALSE) == nc)
Nice, wasn't aware of that :) - great, thanks for the explanation!

2024-02-19 12:10 UTC, jorainer commented on R/Spectra.R
> +#'    based on specified ranges for *any* values of `spectraVariables(object)`.
Yes, that makes sense.

2024-02-19 12:15 UTC, jorainer approved these changes
Thanks Phili! This function makes a lot of sense to me!

2024-02-19 13:49 UTC, jorainer commented
Thanks for the review @lgatto ! Regarding the name, if I understand you you would like to name the function to something like `filterSpectraDataRanges`? Or could you provide a possible example for the name?

I would not use `spectraData` in the name of the function - I would understand that I would filter/subset the `spectraData` (i.e. remove certain columns of `spectraData`) instead of filtering the `Spectra`.

To me `filterRanges` would make sense, because we want to filter the `Spectra` using values in one or more `spectraVariables` (hence the name of that parameter being `spectraVariables`). Also, for the other method we would use `filterValues`. And yes, the idea was in fact that the method should be similar to e.g. `filterPrecursorMzRange` or `filterPrecursorMzValue`, so the user would find/understand the method right away. In facto `filterPrecursorMzRange` would be the same as calling `filterRanges(, spectraVariable = "precursorMz", ...)`.

We also thought of a generic `filterSpectra` method and a `RangeFilter` parameter - that would be another possibility, but then we would add a new S4 object (`RangeFilter`) and hence increase the complexity of `Spectra`...

2024-02-19 15:23 UTC, lgatto commented
OK for `filterRanges()`, you convinced me. Please make sure in the documentation that `filterPrecursorMzRange()` and  `filterRanges(, spectraVariable = "precursorMz", ...)` are equivalent.

2024-02-19 15:54 UTC, philouail commented
Thanks @lgatto for the feedback ! I will adjust the documentation and the code accordingly. As well as adding the `filterValues()` function and a explanation in the vignette. I will try to make it as clear as possible how they can be used :) Putting it in draft for now while i prepare it !

2024-02-21 13:29 UTC, jorainer commented on R/Spectra.R
> +                      stop("'spectraVariables' need to correspond to colnames of",
Maybe specifically mention that we mean the *parameter* spectraVariables would help? I would keep/use the name `spectraVariables` for the parameter and then in the error message say that `One or more values passed with parameter 'spectraVariables' are not available as spectra variables in object. Use the 'spectraVariables()' function to list possible values.`.

just a suggestion...

2024-02-28 16:01 UTC, philouail commented
So here is everything updated. I moved the main code to the MsBackend.R  to have a similar implementation as the other filtering functions. 

Some things i am not 100% sure about: 

- location of unit tests : is test_Spectra.R fine ?
- Should `tolerance` be by default `Inf` ? In `mclosest()` it is but `filterPrecursorMzValue()` is set as 0. 
- the param `values` name ? there is already a `value` one, just want to be sure it's not confusing.

Also curiosity question but what is the different between `filterPrecrusorMz`, `filterPrecursorMzValue`, and `filterPrecursorMzRange`.

I will write the vignette now while i wait for feedback :) Thanks again for the help !

2024-02-29 08:07 UTC, jorainer commented
Regarding your last question: `filterPrecursorMz` and `filterPrecursorMzValues` are the same (i.e. match/filter based on similarity of the precursor m/z). Both (should?) support to match against multiple *target* m/z values (e.g. `filterPrecursorMzValues(sps, mz = c(123.3, 234.2))` to keep spectra with a precursor m/z that matches any of the provided values). The `filterPrecursorMzRange` allows to define a broader range (i.e. precursor m/z within a specified range).

2024-02-29 08:11 UTC, jorainer commented
For the default of `tolerance`. For `filterValues` I would use `0` as default. also for other methods (`filterPrecursorMzValues`) we have `0`. The `mclosest` (and `closest`) are a bit different than these filter functions: from a filter function I would expect to subset the data based on a (stringent) condition. From `closest` `mclosest` I would just like to get the *most similar* hits. The `tolerance` there is essentially a way to define that something is too different to be considered *close*. Hope this does make sense?

2024-02-29 10:41 UTC, jorainer requested changes
Looks good @philouail ! Thanks! I have some change requests - mostly related to documentation - and one suggestion to maybe add an additional parameter to both functions that allows to combine the multiple filters/conditions either with a logical and (the default) or a logical or.

2024-03-06 08:21 UTC, jorainer requested changes
Really great contribution Phili! Thanks! 

I'm totally fine with the implementations, but have some suggestions to improve/fix the documentation.

2024-03-06 08:21 UTC, jorainer commented on R/Spectra.R
> +#' - `filterRanges`: allows filtering of the `Spectra` object based on user
please update the help for `filterRanges` and `filterValues` with the updated versions suggested in `MsBackend.R` (except of the "default implementation" mention.

2024-03-06 08:21 UTC, jorainer commented on R/Spectra.R
> +#' @param condition For `filterRanges` and `filterValues` (default "all") can
also this, please update with the documentation in MsBackend.R

2024-03-06 08:21 UTC, jorainer commented on R/Spectra.R
> +#' - For `filterRanges` and `filterValues`: A `character` vector specifying the
maybe also mention:

... vector specifying the column(s) from `spectraData(object)` on which to filter the data and that correspond to the ...

2024-03-06 08:21 UTC, jorainer commented on tests/testthat/test_Spectra.R
> +                              ranges = c(30, 350, 200,500, 350, 600)))
please for `expect_error` always also check for the error message - that the one you expect is thrown. In this case simply do `expect_error(... , "character")` (i.e. use one of the words from the error message that is thrown).

2024-03-06 08:21 UTC, jorainer commented on vignettes/Spectra.Rmd
> +  available `spectraVariables` in object. if multiple ranges/spectra variables
Please use `. If multiple ...` and maybe also update with the suggested change for the documentation above for MsBackend.R

2024-03-06 08:21 UTC, jorainer commented on vignettes/Spectra.Rmd
> +In this example, we use the filterValues function to retain spectra with a base
please use the back ticks (\`) here around `filterValues`

2024-03-06 08:21 UTC, jorainer commented on vignettes/Spectra.Rmd
> +sps_sub <- filterValues(sps_sciex, spectraVariables = c("basePeakMZ", "rtime"),
Nice example with the base peak m/z - was not even aware that we have that spectra variable - and we definitely don't have a filter function for that particular variable.

Only, please always add a whitespace after the `,` to make the code a little more readable.

2024-03-06 08:21 UTC, jorainer commented on vignettes/Spectra.Rmd
> +Only one spectrum matches all the ranges. Another option for filterValues and
please always add backticks around actual function (or object) names as well as for R code, such as `condition = "any"`.

2024-03-06 08:21 UTC, jorainer commented on vignettes/Spectra.Rmd
> +Let's run the code oncwe again but change the condition parameter this time:
oncwe -> once

2024-03-06 08:51 UTC, philouail commented on R/MsBackend.R
> +#' @param condition For `filterRanges` and `filterValues` (default "all") can
I agree with the naming of the param ! it makes much more sense

2024-03-07 13:09 UTC, jorainer approved these changes
Thanks Phili! All good from my side!

2024-03-11 10:50 UTC, philouail commented on R/MsBackend.R
> +#' @param ranges for `filterRanges`: A `numeric` vector of paired values (upper
So `ranges` length is not finite, it's lenght should be 2*spectraVariables if that helps to make sense. Essentially the values go 2 by 2 but ranges can be as long as the user wants. I can try to improve the overall definition of filterRanges to make that more clear maybe ? I'm also hoping that the examples and vignette helps ?

2024-03-11 10:51 UTC, philouail commented on R/MsBackend.R
> +#'     For `filterValues`: `numeric` of any length allowing to define
Yes I can do that in the next push !

2024-03-11 12:16 UTC, lgatto commented on R/MsBackend.R
> +#' @param ranges for `filterRanges`: A `numeric` vector of paired values (upper
Yes, that's ok then, thanks.

2024-03-11 12:16 UTC, lgatto approved these changes

2024-03-11 12:18 UTC, lgatto commented
Thank you @philouail for the great contribution!

2024-03-11 12:39 UTC, jorainer commented on R/MsBackend.R
> +#'     For `filterValues`: `numeric` of any length allowing to define
yes, that makes sense - can you then please do that for all functions - so that we have everything consistent.

2024-03-11 15:26 UTC, merged